version: "3.8"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=BenchCoder
      - POSTGRES_USER=BenchCoder_user
      - POSTGRES_PASSWORD=BenchCoder_password
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 BenchCoder.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://BenchCoder_user:BenchCoder_password@db:5432/BenchCoder
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://BenchCoder_user:BenchCoder_password@db:5432/BenchCoder
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
  redis_data:
