# Generated by Django 4.2 on 2025-10-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='ai_status',
            field=models.CharField(default='Not Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error'), ('PE', 'Presentation Error'), ('OT', 'Other'), ('P', 'Pending')], default='P', max_length=20),
        ),
    ]
